(function(){var h=void 0,o=!0,p=null,t=!1;
window.EDRUtility={t:function(b,e){function d(){}d.prototype=e.prototype;b.prototype=new d;b.Tc=e.prototype;b.prototype.constructor=b},J:function(b,e){b.style.setAttribute?b.style.setAttribute("cssText",e):b.setAttribute("style",e)},ta:function(b,e){if(b.styleSheet)b.styleSheet.cssText=e;else{if(b.hasChildNodes())for(;1<=b.childNodes.length;)b.removeChild(b.firstChild);b.appendChild(document.createTextNode(e))}},Rc:function(b,e){var d;b.currentStyle?d=b.currentStyle[e]:window.getComputedStyle&&(d=
document.defaultView.getComputedStyle(b,p).getPropertyValue(e));return d},sc:function(b,e,d){b.addEventListener?b.addEventListener(e,d,t):b.attachEvent?(b["e"+e+d]=d,b[e+d]=function(){var l=window.event;b["e"+e+d]({target:l.srcElement,type:l.type})},b.attachEvent("on"+e,b[e+d])):b["on"+e]=b["e"+e+d]},tc:function(b,e,d){for(var l=0;l<e.length;++l)this.sc(b,e[l],d)},matchesSelector:function(b,e){for(var d=document.querySelectorAll(e),l=0;l<d.length;++l)if(d[l]===b)return o;return t},Db:function(b){b=
b.getBoundingClientRect();return{x:b.left,y:b.top}},Ra:function(){var b=0,e=0;window.innerWidth?(b=window.innerWidth,e=window.innerHeight):0!==document.documentElement.clientWidth?(b=document.documentElement.clientWidth,e=document.documentElement.clientHeight):(b=document.body.clientWidth,e=document.body.clientHeight);return{x:b,y:e}},pa:function(b,e,d,l){if(d){var i=new Date;i.setTime(i.getTime()+864E5*d);d="; expires="+i.toGMTString()}else d="";b=b+"="+e+d+"; path=/";l&&(b+=";domain="+l);document.cookie=
b},sa:function(b,e){for(var d=b+"=",l=document.cookie.split(";"),i=[],f=0;f<l.length;f++){for(var j=l[f];" "===j.charAt(0);)j=j.substring(1,j.length);0===j.indexOf(d)&&i.push(j.substring(d.length,j.length))}return 0===i.length?p:e?i.join(e):i[0]},Ac:function(b){this.pa(b,"",-1)},uc:function(){var b=t;this.pa("edr_sc_tst","tst_val",1);this.sa("edr_sc_tst")!==p&&(b=o,this.Ac("edr_sc_tst"));return b},Cc:function(){function b(b){b=b.match(/[\d]+/g);b.length=3;return b.join(".")}var e=p;if(navigator.plugins&&
navigator.plugins.length){var d=navigator.plugins["Shockwave Flash"];d&&d.description?e=b(d.description):navigator.plugins["Shockwave Flash 2.0"]&&(e="2.0.0.11")}else if(navigator.mimeTypes&&navigator.mimeTypes.length)(d=navigator.mimeTypes["application/x-shockwave-flash"])&&d.enabledPlugin&&(e=b(d.enabledPlugin.description));else try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),e=b(d.GetVariable("$version"))}catch(l){try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),e="6.0.21"}catch(i){try{d=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),e=b(d.GetVariable("$version"))}catch(f){}}}return e?e:p},Bb:function(b){if(p===b||"object"!==typeof b)return b;var e=b.constructor(),d;for(d in b)b.hasOwnProperty(d)&&(e[d]=this.Bb(b[d]));return e},dc:0,Kb:function(b,e,d,l,i){function f(){function d(){var c=p;try{c=m.contentDocument||m.document}catch(a){}c?setTimeout(d,10):(document.body.removeChild(f),document.body.removeChild(document.getElementById(j)),l&&l())}i=i||"post";var f=document.createElement("form");
f.setAttribute("method",i);f.setAttribute("action",b);for(var q in e)if(e.hasOwnProperty(q)){var k=document.createElement("input");k.setAttribute("type","hidden");k.setAttribute("name",q);var s=e[q],s="object"===typeof s?JSON.stringify(s):s;k.setAttribute("value",s);f.appendChild(k)}f.setAttribute("target",j);document.body.appendChild(f);f.submit();setTimeout(d,10)}var j="iframe_req_"+ ++this.dc,m=document.createElement("iframe");if(d=d&&"Microsoft Internet Explorer"===navigator.appName)m.src="javascript:void((function(){document.open();document.domain='"+
document.domain+"';document.close();})())";m.setAttribute("id",j);m.setAttribute("name",j);this.J(m,"position:absolute;left:-100000px;top:-100000px;");document.body.appendChild(m);window.frames&&window.frames[j]&&(m=window.frames[j]);m.name=j;d?setTimeout(f,1):f()},Bc:function(){function b(){return(65536*(1+Math.random())|0).toString(16).substring(1)}return b()+b()+"-"+b()+"-"+b()+"-"+b()+"-"+b()+b()+b()},Oa:function(b,e){if(Array.prototype.indexOf)return b.indexOf(e);if(b===p)throw new TypeError;
var d=Object(b),l=d.length>>>0;if(0===l)return-1;var i=0;2<arguments.length&&(i=Number(arguments[2]),i!=i?i=0:0!==i&&(Infinity!==i&&-Infinity!==i)&&(i=(0<i||-1)*Math.floor(Math.abs(i))));if(i>=l)return-1;for(i=0<=i?i:Math.max(l-Math.abs(i),0);i<l;i++)if(i in d&&d[i]===e)return i;return-1}};(function(b){var e=b.EDRUtility,d={zc:function(b){var e={};if(b)for(var f in b)if(b.hasOwnProperty(f)){var j=d.d.create(f,b[f]);j&&(e[f]=j)}return e},execute:function(b,e,d){var j={},m;for(m in e)if(e.hasOwnProperty(m)){var n=e[m];if("push"==n.o.kind){var v=d[n.o.code];n.ra=v!==h?v:p}j[m]=n.$(b)}return j},d:function(b,e){this.o=e;this.ra=p}};d.d.create=function(b,e){switch(e.kind){case "resultHistory":return new d.d.xa(b,e);case "cookieValue":case "elementContent":case "pageUrl":return new d.d.ea(b,
e);case "cookieExists":case "elementExists":case "elementVisible":return new d.d.ba(b,e);case "elementCount":return new d.d.da(b,e);case "push":switch(e.type){case "bool":return new d.d.ba(b,e);case "string":return new d.d.ea(b,e);case "number":return new d.d.da(b,e);default:return p}default:return p}};d.d.ea=function(b,e){try{this.rb=e.regex?RegExp(e.regex):p}catch(f){}this.sb=t;this.tb=0;this.rc=e.visibleOnly===o;e.returnAll?this.sb=o:this.tb=e.index?e.index:0;d.d.call(this,b,e)};e.t(d.d.ea,d.d);
d.d.ea.prototype.$=function(b){var d=[];switch(this.o.kind){case "cookieValue":(b=e.sa(this.o.cookieName))&&d.push(b);break;case "elementContent":for(var b=b.document.querySelectorAll(this.o.selector),f=0;f<b.length;++f)this.rc&&0===b[f].offsetWidth||d.push(b[f].textContent||b[f].innerText);break;case "pageUrl":d.push(b.document.location.href);break;case "push":d.push(this.ra)}if(this.rb){b=[];for(f=0;f<d.length;++f){var j=this.rb.exec(d[f]);if(j&&1===j.length)b.push(d[f]);else if(j)for(var m=1;m<
j.length;++m)b.push(j[m])}d=b}if(this.sb)return d;b=this.tb;return 0>b?p:b>=d.length?p:d[b]};d.d.ba=function(b,e){d.d.call(this,b,e)};e.t(d.d.ba,d.d);d.d.ba.prototype.$=function(b){var d=t;switch(this.o.kind){case "cookieExists":d=e.sa(this.o.cookieName)!==p;break;case "elementExists":d=b.document.querySelector(this.o.selector)!==p;break;case "elementVisible":for(var b=b.document.querySelectorAll(this.o.selector),f=0;f<b.length;++f)if(0!==b[f].offsetWidth){d=o;break}break;case "push":d=this.ra}this.o.not&&
(d=!d);return d};d.d.da=function(b,e){d.d.call(this,b,e)};e.t(d.d.da,d.d);d.d.da.prototype.$=function(b){switch(this.o.kind){case "elementCount":return b.document.querySelectorAll(this.o.selector).length;case "push":return this.ra}};d.d.xa=function(b,e){this.Zb=e.allowDuplicates===o;this.ec=d.d.create(b+"_inner",e.innerProbe);this.kb=p;this.O=[];d.d.call(this,b,e)};e.t(d.d.xa,d.d);d.d.xa.prototype.$=function(b){b=this.ec.$(b);if(JSON.stringify(b)===JSON.stringify(this.kb))return this.O;this.kb=b;
for(var b="[object Array]"===Object.prototype.toString.call(b)?b:[b],e=0;e<b.length;++e){if(!this.Zb){for(var d=t,j=0;j<this.O.length;++j)if(b[e]===this.O[j].val){d=o;break}if(d)continue}this.O.push({dt:Math.round((new Date).getTime()/1E3),val:b[e]})}return this.O};this.EDRSurveyCodeProbes=d})(window);(function(b,e,d,l){var i={fc:0,Rpc:function(d,j){if(j.local)for(var m in j.local)if(j.local.hasOwnProperty(m)){var n=j.local[m];"function"===typeof n&&(j.local[m]={method:n})}m="edr"+i.fc++;n=e.createElement("iframe");n.id=n.name=d.props.id;n.border=n.frameBorder=0;n.allowTransparency=o;n.src=d.remote+"&xdm_o="+l(i.hb(b.location.toString()))+"&xdm_c="+m;e.getElementById(d.container).appendChild(n);return new i.Xb(d,j,n,i.hb(d.remote),m)},hb:function(b){var e=b.toLowerCase().match(/^((http.?:)\/\/([^:\/\s]+)(:\d+)*)/),
b=e[2],d=e[3],e=e[4]||"";if("http:"===b&&":80"===e||"https:"===b&&":443"===e)e="";return b+"//"+d+e},Xb:function(e,i,l,n,v){function q(a){var g=Array.prototype.slice;return function(){var c={method:a,params:g.call(arguments,0)};l.contentWindow.postMessage(JSON.stringify(c),n)}}function k(a){if(a.origin===n&&(a=JSON.parse(a.data),a.channel===v))if(a.internal)!s&&"-ready-"===a.internal&&(d(e.onReady,0),s=o);else{var g=i.local[a.method];g.method.apply(g.scope,a.params)}}var s=t,c;for(c in i.remote)i.remote.hasOwnProperty(c)&&
(this[c]=q(c));b.addEventListener?b.addEventListener("message",k,t):b.attachEvent("onmessage",k)}};this.eDRXDMClient=i;this.eDRXDMClient.Rpc=i.Rpc})(window,document,window.setTimeout,encodeURIComponent);/*
 eDigitalResearch survey code v7.0.3.7
   Copyright (C) 2012 eDigitalResearch all rights reserved.
   http://www.edigitalresearch.com
*/
(function(b,e,d,l,i,f,j,m,n,v){var q=this,k=b.EDRUtility,s=b.EDRSurveyCodeProbes;if("undefined"!=typeof q.EDRSurvey)q.EDRSurvey.Fb().log(33,p,p,4);else{var c={A:{Sc:0,H:t,vb:p,Fc:function(){this.vb=new Date;this.H=e.location.hostname!==e.domain;if(!this.H){var a=e.createElement("iframe");e.body.appendChild(a);a.parentNode.removeChild(a)}},Ec:function(){return new Date-this.vb}},c:function(a){function g(){m.z=e.getElementById(m.jb);m.z?(m.z.setAttribute("scrolling","no"),m.z.setAttribute("title","Online Quality Survey"),
c.a.Kc(a,m),m.K=l(function(){c.b.log(12,m.g,p,4);m.s()},m.Wb),m.X()):l(g,10)}a=a?a:p;this.Wb=3E4;this.Ya=2E3;this.ca="position:absolute;left:-100000px;top:-100000px;width:100%;height:100%;";this.g=(this.id=a)?a:"initial";this.z=this.p=this.name=p;this.Y=this.w=t;this.M=this.G=p;this.ha="edr_lwrap_"+(a?a:"first");this.jb="edr_l_"+(a?a:"first");this.T=this.j=this.B=p;this.v={};this.ma=p;this.P=t;this.i=p;this.ja=[];this.n=[];this.S=this.K=p;this.ka=t;this.Da=this.h=p;this.Ja={};this.la=p;this.Ea=t;
var r="undefined"!==typeof b.postMessage&&b.postMessage!==p,d={xdm:r&&b.eDRXDMClient?"edr":b.easyXDM?"easy":"none"};a&&(d.lid=a);c.b.log(5,this.g,d.xdm);var u=this.p=e.createElement("div"),r=r&&b.eDRXDMClient?b.eDRXDMClient:b.easyXDM?b.easyXDM:b.eDRXDMClient,i=e.getElementsByTagName("head")[0],j=this.M=e.createElement("style"),f=this,n;u.id=this.ha;u.className="edr_lwrap";e.getElementById("edr_survey").appendChild(u);this.G=n=new r.Rpc({remote:c.a.wc("l",d),swf:c.a.I+"inc/easyxdm.swf",container:this.ha,
props:{id:this.jb},onReady:function(){n.hostReady()}},{remote:{alertMessage:{},hostReady:{},onShown:{},onHidden:{},requestMetrics:{},onAnchorEdgesChanged:{},hide:{},prepareSurvey:{}},local:{alertMessage:function(a){alert("received by survey code: "+a)},configureLayer:function(a,g,c,b,r,e){f.yc(a,g,c,b,r,e)},hide:function(){f.Sa()},forceHide:function(){f.Z()},destroyLayer:function(){f.s()},deployAdditionalLayers:function(a){for(var g=0;g<a.length;g++)c.a.Pa(a[g])},triggerLayerByName:function(a){(a=
c.a.Eb(a))&&a.Xa(f.p)},setMetrics:function(a,g){f.nc(a,g)},activateTestMode:function(a){c.b.zb(a)},execute:function(){f.execute()},logServerItems:function(a){for(var g=0;g<a.length;++g)c.b.Nc(f.g,a[g])},updateCookie:function(a){k.pa(EDRSurvey.COOKIE_NAME,a,36500,c.a.DOMAIN)},log:function(a,g){c.b.Lc(f.g,a,g)}}});j.type="text/css";i.appendChild(j);k.ta(j,"#"+this.ha+" {"+this.ca+"}");var m=this;g();c.b.log(6,this.g)}};c.c.prototype.getName=function(){return this.name};c.c.prototype.Mc=function(){this.G.requestMetrics()};
c.c.prototype.Ic=function(a){this.G.onAnchorEdgesChanged(a)};c.c.prototype.yc=function(a,g,b,d,u,f){c.b.log(7,this.g,a);this.name=a;this.z.className="edr_layer_name_"+a;this.B=g;this.T=d;this.v=u;this.Ja=f;d.lightbox&&!this.h?(a=e.createElement("div"),a.className="edr_lb",e.getElementById("edr_survey").appendChild(a),this.h=a):!d.lightbox&&this.h&&(this.h.parentNode.removeChild(this.h),this.h=p);this.n=[new c.Za];this.ja=[];if(b){a=b.triggers;b=b.globalConditionals;if(a)for(g=0;g<a.length;++g)this.n.push(c.f.create(a[g]));
if(b)for(g=0;g<b.length;++g)this.ja.push(c.q.create(b[g]))}var b="#"+this.ha+"{",b=b+(this.ca+"z-index:"+c.a.fa+";"),j;for(j in this.B)this.B.hasOwnProperty(j)&&(b+=j+":"+this.B[j]+";");k.ta(this.M,b+"}");c.e.D(c.e.Tb,this);this.P?this.w&&this.La(this.i):(this.P=o,i(this.K),this.K=p)};c.c.prototype.ub=function(a,g,c){k.J(a,"background-color:"+c+";opacity:"+g+";filter: alpha(opacity="+Math.round(100*g)+");display:block;")};c.c.prototype.wb=function(a,g){var c=this.T.lightbox,b=parseFloat(c.opacity);
j(this.Da);var e=a?1:0,d=this;this.Da=f(function(){d.ub(d.h,e*b,c.colour);e+=!a?0.05:-0.05;if(!a&&1<=e||a&&0>=e)j(d.Da),g&&g()},10)};c.c.prototype.oc=function(){if(this.h){var a=this.T.lightbox;a.fade?this.wb(t):this.ub(this.h,a.opacity,a.colour)}};c.c.prototype.cc=function(){if(this.h){var a=this,g=function(){k.J(a.h,"")};this.T.lightbox.fade?this.wb(o,g):g()}};c.c.prototype.Xa=function(a){this.n[0].aa(a)};c.c.prototype.qa=function(a){if(this.P){"click"===a.type&&a.target&&a.target.className===c.a.N&&
this.j&&this.j.Hc(a.target)&&this.execute();for(var g=0;g<this.n.length;++g)this.n[g].qa(a,c.A,this)}};c.c.prototype.X=function(){i(this.ma);if(this.P){var a={layer:this,canShow:o};c.e.D(c.e.Pb,a);if(a=a.canShow)for(var g=0;g<this.ja.length;++g){if(!this.ja[g].Ib(p)){a=t;break}}else this.Ea||(c.b.log(31,this.g,p,4),this.Ea=o);if(a){if(this.S)this.La(this.S===o?p:this.S);else{for(a=0;a<this.n.length;++a)this.n[a].evaluate(c.A,this);for(var g=p,r=t,e=t,a=0;a<this.n.length;++a)if(this.n[a].xc()){var r=
o,d=this.n[a].i;d&&(e=o,d!==b&&(g=d))}r&&(this.w&&(g&&g!==this.i)&&this.Z(o),e&&!this.w?this.La(g):!e&&this.w&&this.Sa())}this.S=p}else this.w&&(this.S=this.i?this.i:o,this.Z(o))}var f=this;this.ma=l(function(){f.X()},100)};c.c.prototype.La=function(a){c.b.log(8,this.g,a);if(this.P){var g=k.Bb(this.T),r=g.position.relativeTo;if(r){switch(r){case "window":r=b;break;case "document":r=b.document;break;default:r="trigger"===r?a:e.querySelector(r),r||(r=b,g.position.edges=["top","left","bottom","right"],
g.position.offset={x:0,y:0})}if(this.w){if(!this.j)throw"EDRSurveyCode.PositionedLayer not available when showing in show()";this.j.s()}else k.J(this.p,this.ca),this.oc();this.j=new c.l(this,r,this.B,g);this.w=o;this.Y||k.Kb(c.a.I+"log.php?e=layershow",this.v,c.A.H);this.i=a;this.G.onShown();c.e.D(c.e.Ub,{layer:this,firstShow:!this.Y});this.Y=o}else this.s()}};c.c.prototype.Sa=function(){if(!this.ka){c.b.log(9,this.g);this.ka=o;this.cc();this.G.hide();var a=this;b.setTimeout(function(){a.ka&&(c.b.log(13,
a.g,[a.Ya],4),a.Z())},this.Ya)}};c.c.prototype.Z=function(a){this.ka=t;if(this.w){c.b.log(10,this.g);if(!a)for(a=0;a<this.n.length;++a)this.n[a].Wa();k.J(this.p,this.ca+"visibility:hidden;");this.i=this.Ea=this.w=t;this.j&&(this.j.s(),this.j=p);this.G.onHidden();c.e.D(c.e.Sb,{layer:this})}};c.c.prototype.nc=function(a,g){this.j&&this.j.Pc(a,g)};c.c.prototype.s=function(){c.b.log(11,this.g);i(this.ma);this.K&&i(this.K);this.j&&this.j.s();this.z&&this.z.parentNode.removeChild(this.z);this.M&&this.M.parentNode.removeChild(this.M);
this.p&&this.p.parentNode.removeChild(this.p);this.h&&this.h.parentNode.removeChild(this.h);this.h=this.G=this.M=this.p=this.z=this.j=this.K=this.ma=p;c.a.Jc(this.id);c.e.D(c.e.Qb,{layerName:this.getName()})};c.c.prototype.execute=function(){if(this.v)switch(c.e.D(c.e.Rb,{layer:this,action:this.v.type}),this.v.type){case "triggerOtherLayer":var a=c.a.Eb(this.v.otherLayerName);a&&a.Xa(this.p);break;case "popupSurvey":this.ab(this.v);this.s();break;case "exitSurvey":this.ac(this.v),this.s()}else this.s()};
c.c.prototype.ab=function(a,g){var b=k.Bc(),e=this.ib();e.surveyId=a.surveyId;e.installationId=a.installationId;e.deploymentId=a.deploymentId;k.Kb(c.a.I+"prepare.php?guid="+b,e,c.A.H);e=this.v.windowSize;b=c.a.I+"deploy/"+(g?"enter-exit-survey-no-holding":"enter")+"/guid/"+b;g?(g.location=b,e.x&&e.y&&(g.resizeTo?g.resizeTo(e.x,e.y):(g.outerWidth=e.x,g.outerHeight=e.y)),this.la=g):this.la=this.ob(b,"edr_win_"+this.name,e.x,e.y)};c.c.prototype.ac=function(a){function g(d){if(100<++u)d.close(),d=p,c.b.log(24,
i.g,p,3);else{try{if(!d.document)throw"wait";}catch(w){l(function(){g(d)},20);return}if(d.document.getElementById){c.b.log(27,i.g);try{var f=d.document.getElementsByTagName("body");f&&(f[0].innerHTML="")}catch(j){}f=c.a.I+"deploy/holding/deployment/"+a.deploymentId;f+="/survey/"+n(a.surveyId);f+="/installation/"+n(a.installationId);c.A.H&&(f+="/doc-domain/"+n(e.domain));b.locale&&(f+="/locale/"+n(b.locale));d.document.write('<!DOCTYPE html><SCRIPT LANGUAGE="Javascript">'+(c.A.H?'document.domain = "'+
e.domain+'";':"")+"var pc = "+JSON.stringify(i.Ja)+";var ppv = "+JSON.stringify(c.a.Va)+";var sed = "+JSON.stringify(b)+";var dply = "+JSON.stringify(a)+";<\/SCRIPT>");d.document.write('<SCRIPT LANGUAGE="Javascript" SRC="'+f+'"><\/SCRIPT>')}else c.b.log(25,i.g,p,3),i.ab(a,d)}}c.b.log(26,this.g);var b=this.ib();b.surveyId=a.surveyId;b.installationId=a.installationId;b.deploymentId=a.deploymentId;var d=this.v.holdingWindowSize;this.la=this.ob(c.A.H&&"Microsoft Internet Explorer"===navigator.appName?
c.a.Hb:"about:blank","edr_win_"+this.name,d.x,d.y);var u=0,i=this;g(this.la)};c.c.prototype.ib=function(){var a=s.execute(b,s.zc(this.Ja),c.a.Va);return{url:b.location.href,probes:a,locale:c.a.LOCALE,data1:c.a.DATA1,data2:c.a.DATA2,data3:c.a.DATA3,test:c.a.TEST}};c.c.prototype.ob=function(a,g,c,e){var d="location=0,toolbar=no,directories=no,status=no,scrollbars=yes,resizable=yes";c&&e&&(d+=",width="+c+",height="+e);return b.open(a,g,d)};c.f=function(a){this.m=a;this.i=p;this.oa=t;this.Ba=[];if(a=
a.conditionals)for(var g=0;g<a.length;++g)this.Ba.push(c.q.create(a[g]))};c.f.create=function(a){switch(a.type){case "init":return new c.za(a);case "click":return new c.ya(a);case "scroll":return new c.Aa(a);default:c.b.log(16,p,[a.type],2)}};c.f.prototype.evaluate=function(){};c.f.prototype.qa=function(){};c.f.prototype.cb=function(a){for(var g=0;g<this.Ba.length;++g)if(!this.Ba[g].Ib(a))return t;return o};c.f.prototype.aa=function(a){var g=a||b;g!==this.i&&(c.b.log(14,this.m.type,a),this.oa=o,this.i=
g)};c.f.prototype.Wa=function(){this.i&&(c.b.log(15,this.m.type),this.oa=o,this.i=p)};c.f.prototype.xc=function(){var a=this.oa;this.oa=t;return a};c.Za=function(){c.f.call(this,{type:"manual"})};k.t(c.Za,c.f);c.za=function(a){c.f.call(this,a);this.bb=t};k.t(c.za,c.f);c.za.prototype.evaluate=function(a,g){!g.Y&&!this.bb&&(this.cb()?this.m.delay?a.Ec()>parseInt(this.m.delay,10)&&this.aa():this.aa():(c.b.log(17,this.m.type,p,4),this.bb=o))};c.ya=function(a){c.f.call(this,a);this.Na=t};k.t(c.ya,c.f);
c.ya.prototype.qa=function(a,g,b){if("click"===a.type&&this.m.selector&&k.matchesSelector(a.target,this.m.selector))if(this.i&&a.target===this.i)this.Wa();else if(!this.Na)if(this.cb(a.target)){var e=this,g=function(){e.Na=t;e.aa(a.target)};this.m.delay&&!b.w?(this.Na=o,l(g,this.m.delay)):g()}else c.b.log(18,this.m.type,a.target,4)};c.Aa=function(a){this.mc=a.repeatable?o:t;this.eb={update:function(){for(var a=["scrollTop","scrollLeft"],b=0;b<a.length;++b)e.body&&e.body[a[b]]?this[a[b]]=e.body[a[b]]:
e.documentElement&&e.documentElement[a[b]]?this[a[b]]=e.documentElement[a[b]]:e.documentElement&&!e.documentElement[a[b]]&&(this[a[b]]=0)}};c.f.call(this,a)};k.t(c.Aa,c.f);c.Aa.prototype.evaluate=function(a,g){var c=this.m.element;if(c){var d=this.m.axes;if(d){var f={x:"scrollLeft",y:"scrollTop"},i=t,j=function(a,b,g){var c=parseInt(g,10);-1!==g.indexOf("%")&&(c=("y"===b?a.offsetHeight:a.offsetWidth)*(c/100));return c},k=[],l=p;"document"===c?(this.eb.update(),k=[this.eb],l=b.document.body):k=e.querySelectorAll(c);
for(var m=0;m<k.length;++m)for(var n in f)if(f.hasOwnProperty(n)&&d[n]){var s=d[n].lowerBound,q=d[n].upperBound,q=q===p||q===h||k[m][f[n]]<=j(l?l:k[m],n,q);if((s===p||s===h||k[m][f[n]]>=j(l?l:k[m],n,s))&&q){if(this.mc||!g.Y)this.aa("document"===c?b.document.body:k[m]);i=o}}i||this.Wa()}}};c.q=function(a){this.gc=a.matchMode;this.hc=a.not===o;this.xb=a.value};c.q.create=function(a){switch(a.type){case "cookie":return new c.ua(a);case "element":return new c.va(a);case "triggerElement":return new c.wa(a);
default:c.b.log(19,p,[a.type],2)}};c.q.prototype.Ib=function(a){a=this.ia(a);return a=this.hc?!a:a};c.q.prototype.ia=function(){return o};c.ua=function(a){c.q.call(this,a)};k.t(c.ua,c.q);c.ua.prototype.ia=function(){return o};c.va=function(a){c.q.call(this,a)};k.t(c.va,c.q);c.va.prototype.ia=function(){var a=this.gc,b=e.querySelector(this.xb);return b&&1===a?0!==b.offsetWidth:b!==p};c.wa=function(a){c.q.call(this,a)};k.t(c.wa,c.q);c.wa.prototype.ia=function(a){return!a?t:k.matchesSelector(a,this.xb)};
c.l=function(a,b,c,e){this.F=a;this.u=b;this.B=c;this.Ga={};this.Ia={};this.Fa={};this.Ha={};this.V={};this.ga=p;this.L={};var a=e.position.offset||{},b={x:0,y:0},d;for(d in b)if(b.hasOwnProperty(d)){var f=a[d]?"string"===typeof a[d]?a[d]:a[d].toString():"0",c=-1!==f.indexOf("%"),f=parseInt(f,10);this.Fa[d]=c?0:f;this.Ia[d]=c?f:0;this.Ha[d]=0>f;this.Ga[d]=Math.abs(f)+(c?"%;":"px;");this.V[d]=f+(c?"%;":"px;")}this.Ca=e.position.edges;this.na=p;this.pb()};c.l.prototype.Hc=function(a){var b=this.L,c;
for(c in b)if(b.hasOwnProperty(c)&&a===b[c])return o;return t};c.l.prototype.Pc=function(a,b){this.kc(a);this.bc(b)};c.l.prototype.pb=function(){this.F.Mc();this.Yb()};c.l.prototype.kc=function(a){if(this.u)if(0===this.u.offsetWidth)this.F.Z();else{var c="";this.B.width||(c+="width:"+a.x+"px;");this.B.height||(c+="height:"+a.y+"px;");switch(this.u){case b:case b.document:c+=this.jc(a);break;default:c=this.Ca?c+this.qb(a,this.Ca,this.V):c+this.ic(a)}k.J(this.F.p,c)}};c.l.prototype.jc=function(a){function c(a){return e?
-1!==k.Oa(e,a):t}var e=this.Ca,d="position:"+(this.u===b?"fixed":"absolute")+";",f=k.Ra();if(c("left")===c("right"))var i=this.Fa.x-Math.min(f.x/2,a.x/2),d=d+("right:auto;left:"+(this.Ia.x+50)+"%;margin-left:"+i+"px;");else c("left")?d+="right:auto;left:"+this.V.x:c("right")&&(d+="left:auto;right:"+(this.Ha.x?"":"-")+this.Ga.x);c("top")===c("bottom")?(a=this.Fa.y-Math.min(f.y/2,a.y/2),d+="bottom:auto;top:"+(this.Ia.y+50)+"%;margin-top:"+a+"px;"):c("top")?d+="bottom:auto;top:"+this.V.y:c("bottom")&&
(d+="top:auto;bottom:"+(this.Ha.y?"":"-")+this.Ga.y);this.lb([]);return d};c.l.prototype.Yb=function(){i(this.na);var a=this;this.na=l(function(){a.pb()},1E3)};c.l.prototype.ic=function(a){var c=k.Db(this.u),b=k.Ra(),c={left:c.x,right:b.x-(c.x+this.u.offsetWidth),bottom:b.y-(c.y+this.u.offsetHeight),top:c.y},c=c.left>a.x||c.right>a.x?c.left>c.right?"left":"right":c.top>c.bottom?"top":"bottom",b=this.V;return this.qb(a,{anchor:[c],layer:[{top:"bottom",right:"left",bottom:"top",left:"right"}[c]]},{x:"right"===
c?b.x:"left"===c?0<b.x.length&&"-"==b.x[0]?b.x.substring(1):"-"+b.x:0,y:"top"===c?b.y:"bottom"===c?0<b.y.length&&"-"==b.y[0]?b.y.substring(1):"-"+b.y:0})};c.l.prototype.qb=function(a,c,b){function e(a,c,b){function d(a){return c?-1!==k.Oa(c,a):t}b=b||{x:a.clientWidth,y:a.clientHeight};a={x:b.x/2,y:b.y/2};d("top")&&(a.y=0);d("bottom")&&(a.y=b.y);d("left")&&(a.x=0);d("right")&&(a.x=b.x);return a}var d=k.Db(this.u),f=e(this.u,c.anchor),i=e(this.F.p,c.layer,a),j=d.x+f.x-i.x,d=d.y+f.y-i.y,f=k.Ra(),j=0>
j?0:j>f.x-a.x?f.x-a.x:j,d=0>d?0:d>f.y-a.y?f.y-a.y:d,a="position:fixed;left:"+j+"px;top:"+d+"px;margin-left:"+b.x+"margin-top:"+b.y;this.lb(c.layer);return a};c.l.prototype.lb=function(a){var c=this.ga===p||this.ga.length!==a.length;if(!c)for(var b=0;b<a.length;++b)if(-1==k.Oa(this.ga,a[b])){c=o;break}c&&(this.ga=a,this.F.Ic(a))};c.l.prototype.bc=function(a){for(var b in a)if(a.hasOwnProperty(b)){var d=a[b],f=e.getElementById(b);f||(delete this.L[b],f=e.createElement("a"),f.id=b,f.href="javascript:void(0)",
f.className=c.a.N,d.title&&(f.title=d.title),d.text&&("undefined"!==typeof f.textContent?f.textContent=d.text:f.innerText=d.text),this.F.p.appendChild(f),this.L[b]=f);k.J(f,"top:"+d.top+"px;left:"+d.left+"px;width:"+d.width+"px;height:"+d.height+"px;")}};c.l.prototype.s=function(){i(this.na);this.F=this.u=this.na=p;for(var a in this.L)if(this.L.hasOwnProperty(a)){var b=e.getElementById(a);b&&b.parentNode.removeChild(b)}this.L={}};c.b={Vb:100,Lb:t,Ma:p,C:p,nb:{},U:[],zb:function(a){a&&(this.nb=a,this.Lb=
o);this.Ma||(a=e.createElement("style"),a.type="text/css",k.ta(a,"#edr_test {font-size:12px;text-align:left;font-family:monospace;position:fixed;bottom:0;left:0;right:0;height:15%;z-index:"+c.a.fa+";background-color:#fff;border-top:1px solid silver;overflow:auto;color:black;}#edr_test ul, #edr_debug_panel li {padding:0;margin:0;list-style-type:none;}#edr_test li span {margin-right:1em;}#edr_test li span.id {font-weight:bold; min-width: 10em;display:inline-block;}#edr_test li.t_3 {color:red;}#edr_test li.t_4 {color:goldenrod;}#edr_test li.s_lcl {background-color:#E9E9FF;}#edr_test li.s_prv {background-color:#FFF7E6;}#edr_test li.s_svr {background-color:#F7E6FF;}#edr_test li.t_2 {color:white;background-color:red;}."+
c.a.N+" {opacity:0.5;display:block;filter: alpha(opacity = 50);background-color:white;outline:1px solid fuchsia;}"),e.getElementsByTagName("head")[0].appendChild(a),a=this.Ma=e.createElement("div"),a.id="edr_test",c.a.fb.appendChild(a),this.C=e.createElement("ul"),a.appendChild(this.C));this.lc()},Gc:function(){return this.Ma!==p},lc:function(){for(;1<=this.C.childNodes.length;)this.C.removeChild(this.C.firstChild);for(var a=0;a<this.U.length;++a)this.mb(this.U[a])},mb:function(a){function b(a){return a===
p?"null":a===h?"undefined":a.nodeName?"Node: "+a.nodeName:a.toString()}var c=e.createElement("li"),d={};switch(a.src){case 0:d.src="lcl";break;case 1:d.src="svr";break;case 2:d.src="prv"}c.className="t_"+a.type+" "+("s_"+d.src);d.dt=a.Qa.toLocaleTimeString();a.id&&(d.id=a.id);if(a.Ta)d.msg=a.Ta;else{var f=a.Ua instanceof Array?a.Ua:[a.Ua],i=this.nb[a.Ab];if(i){for(a=0;a<f.length;++a)i=i.replace("{"+a+"}",b(f[a]));d.msg=i}else{d.code=a.Ab;for(a=0;a<f.length;++a)d["par_"+a]=b(f[a])}}for(var j in d)d.hasOwnProperty(j)&&
(f=e.createElement("span"),f.className=j,f.innerText=f.textContent=d[j],c.appendChild(f));this.C.insertBefore(c,this.C.firstChild)},log:function(a,b,c,d){d===h&&(d=6);this.Ka({Qa:new Date,src:0,type:d,id:b,Ab:a,Ua:c})},Lc:function(a,b,c){c===h&&(c=6);this.Ka({Qa:new Date,src:2,type:c,id:a,Ta:b})},Nc:function(a,b){this.Ka({Qa:new Date(1E3*b.dt),src:1,type:b.type,id:a,Ta:b.msg})},Ka:function(a){this.U.push(a);this.C?this.mb(a):this.U.length>this.Vb&&this.U.pop()}};c.e={Nb:"beforeInitialised",Ob:"initialised",
Tb:"layerInitialised",Pb:"layerCanShow",Ub:"layerShown",Sb:"layerHidden",Qb:"layerDestroyed",Rb:"layerExecuted",r:[],vc:function(a,b){if("function"!==typeof b||-1!==this.gb(a,b))return t;this.r.push({Cb:a,Gb:b});return o},detach:function(a,b){var c=this.gb(a,b);if(-1===c)return t;var d=this.r.slice(c+1||this.r.length);this.r.length=0>c?this.r.length+c:c;this.r.push.apply(this.r,d);return o},D:function(a,b){for(var c=0;c<this.r.length;++c){var d=this.r[c];if(d.Cb===a)try{d.Gb.call(q,b||p)}catch(e){}}},
gb:function(a,b){for(var c=0;c<this.r.length;++c){var d=this.r[c];if(d.Cb===a&&d.Gb===b)return c}return-1}};c.a={REMOTE_HOST:p,REMOTE_PATH:p,ID:p,LOCALE:p,DATA1:p,DATA2:p,DATA3:p,TEST:t,VERSION:p,PROPORTION:p,DOMAIN:"",fa:999999,N:"edr_go",I:p,k:{},Hb:b.location,Va:{},fb:p,Q:t,R:p,W:p,Jb:function(){c.b.log(1);var a=e.domain;this.DOMAIN?-1===a.indexOf(this.DOMAIN,a.length-this.DOMAIN.length)&&(c.b.log(29,p,this.DOMAIN,3),this.DOMAIN=a):this.DOMAIN=a;c.b.log(28,p,this.DOMAIN);this.X();var b=this;f(function(){b.X()},
500);this.yb(1)},yb:function(a){c.b.log(2,p,a);var b=this;/in/.test(e.readyState)?l(function(){b.yb(a+1)},9):this.$a(1)},$a:function(a){var b={wait:t,abort:t};c.e.D(c.e.Nb,b);if(!b.abort)if(b.wait){var d=this;c.b.log(30,p,a);l(function(){d.$a(a+1)},100+500*(a-1))}else this.pc()},pc:function(){c.b.log(3);var a=b.ecos_sid,d=b.ecos_vault;a&&d&&c.b.log(32,p,"ESV-"+("_"!==d?d+"-":"")+a,4);c.A.Fc();this.Q=k.uc();this.R=k.Cc();this.W=this.qc(this.Q,this.R);c.b.log(4,p,[this.Q,this.R,this.W],this.W?6:2);
this.I=("https:"===e.location.protocol?"https://":"http://")+this.REMOTE_HOST+this.REMOTE_PATH;a=e.getElementsByTagName("head")[0];d=e.createElement("style");d.type="text/css";a.appendChild(d);k.ta(d,"#edr_survey .edr_lwrap iframe {width:100%;height:100%;}#edr_survey ."+this.N+" {opacity:0;display:block;filter:alpha(opacity = 0);position:absolute;font-size:0;background-color:#000;margin:0;padding:0;z-index:"+(this.fa+1)+";}#edr_survey ."+this.N+":focus {opacity:1;filter:alpha(opacity = 50);background-color:rgba(0, 0, 0, 0.1);}#edr_survey .edr_lb {position:fixed;top:0;left:0;right:0;bottom:0;z-index:"+
(this.fa-1)+";display:none;}");a=this.fb=e.createElement("div");a.id="edr_survey";e.body.appendChild(a);this.TEST&&c.b.zb();this.$b(e);c.e.D(c.e.Ob,{supportedPlatform:this.W});this.Pa()},X:function(){k.pa("ecos.dt",+new Date,p,this.DOMAIN)},$b:function(a){var b=this;k.tc(a,["click"],function(a){for(var c in b.k)b.k.hasOwnProperty(c)&&b.k[c].qa(a)})},Kc:function(a,b){this.k[a]=b},Jc:function(a){delete this.k[a]},Pa:function(a){var b=this.k[a];b||(b=new c.c(a));return b},Eb:function(a){for(var b in this.k)if(this.k.hasOwnProperty(b)&&
this.k[b].name===a)return this.k[b];return p},wc:function(a,d){var f=this.I+a+".php?id="+this.ID;this.W||(f+="&s=0");c.b.Gc()&&(f=f+"&t="+(c.b.Lb?2:1));for(var f=f+("&v="+this.VERSION),i="",j=b.location.href,m=0,l=0;l<j.length;l++)"/"===j.charAt(l)&&m++,3<=m&&(i+=j.charAt(l));0<this.LOCALE.length&&(f+="&l="+n(this.LOCALE));0<this.DATA1.length&&(f+="&d1="+n(this.DATA1));0<this.DATA2.length&&(f+="&d2="+n(this.DATA2));0<this.DATA3.length&&(f+="&d3="+n(this.DATA3));0<screen.width&&0<screen.height&&(f+=
"&x="+screen.width+"&y="+screen.height);0<screen.colorDepth&&(f+="&d="+screen.colorDepth);this.Q&&(f+="&c="+n(k.sa(EDRSurvey.COOKIE_NAME,".")));f+="&ck="+(this.Q?"1":"0");this.R!==p&&(f+="&fl="+n(this.R));1>this.PROPORTION&&(f+="&pr="+this.PROPORTION);f+="&p="+n(i.substring(0,100));e.referrer&&(f+="&ref="+n(e.referrer.substring(0,100)));0<=v.indexOf("Safari")&&(f+="&fu="+n(b.location.href));for(var q in d)d.hasOwnProperty(q)&&(f+="&"+q+"="+n(d[q]));return f},qc:function(a,c){function d(a){return"undefined"!==
typeof a&&a!==p}return!a?t:!d(e.querySelector)||!d(e.querySelectorAll)?t:d(b.postMessage)?d(b.easyXDM)||d(b.eDRXDMClient):6<=(c?c.split(".")[0]:p)&&b.easyXDM!==h&&b.easyXDM!==p},Dc:function(){var a=[],b;for(b in this.k)this.k.hasOwnProperty(b)&&a.push(this.k[b]);return a},Fb:function(){return c.b},Qc:function(a){for(var b in a)a.hasOwnProperty(b)&&this.Mb(b,a[b])},Mb:function(a,b){if(b.substring||b.toFixed||b===o||b===t)this.Va[a]=b.substring?b.toString():b;else throw"Invalid probe value for key: "+
a;},Oc:function(a){if(a.substring)this.Hb=a;else throw"Path must be a string";}};q.EDRSurvey=c.a;c.a.main=c.a.Jb;c.a.setProbeValue=c.a.Mb;c.a.setProbeValues=c.a.Qc;c.a.setDomainAccessDocumentPath=c.a.Oc;c.a.deployLayer=c.a.Pa;c.a.getLayers=c.a.Dc;c.a.getTester=c.a.Fb;c.a.Events=c.e;c.a.Events.attach=c.e.vc;c.a.Events.detach=c.e.detach;c.c.prototype.getName=c.c.prototype.getName;c.c.prototype.hide=c.c.prototype.Sa;c.c.prototype.trigger=c.c.prototype.Xa;c.c.prototype.destroy=c.c.prototype.s;EDRSurvey.REMOTE_HOST=
"edigitalsurvey.com";EDRSurvey.REMOTE_PATH="/";EDRSurvey.COOKIE_NAME="ckps_eds";EDRSurvey.ID="INS-642345567";EDRSurvey.LOCALE="";EDRSurvey.DATA1="";EDRSurvey.DATA2="";EDRSurvey.DATA3="";EDRSurvey.TEST=t;EDRSurvey.VERSION="7038";EDRSurvey.PROPORTION=1;EDRSurvey.DOMAIN="";EDRSurvey.Jb()}})(window,document,location,window.setTimeout,window.clearTimeout,window.setInterval,window.clearInterval,decodeURIComponent,encodeURIComponent,navigator.userAgent);})();

require(['istats-1'], function(istats) {

	EDRSurvey.bbc = {
		hasTaken: null
	};

	// Attach S1 cookie to EDRSurvey when the layer is shown.
	EDRSurvey.Events.attach('layerShown', function(args) {
		EDRSurvey.bbc.hasTaken = false;
		var matches = bbccookies.get().match(/s1=([^;]+)/);
		if (matches[1]) {
			EDRSurvey.DATA3 = matches[1];
		}
	});

	// When the invitation is accepted.
	EDRSurvey.Events.attach('layerExecuted', function(args) {
		EDRSurvey.bbc.hasTaken = true;
		istats && istats.log && istats.log(
			"click",
			"oqs-survey-yes"
		);
	});

	// When the invitation is declined.
	EDRSurvey.Events.attach('layerDestroyed', function(args) {
		if (EDRSurvey && EDRSurvey.bbc && (EDRSurvey.bbc.hasTaken === false)) {
			istats && istats.log && istats.log(
				"click",
				"oqs-survey-no"
			);
		}
	});

});
