define({
    oneHourAgo : '1 hour ago',
    xHoursAgo : '{x} hours ago',
    oneMinuteAgo : '1 minute ago',
    xMinutesAgo : '{x} minutes ago',
    lessThanAMinuteAgo : 'Less than a minute ago',
    changeYourLocation : 'Change your location',
    enterTownPostcode : 'Enter a UK town or postcode',
    loading : 'Loading',
    localNewsAndWeather : 'Local News &amp; Weather',
    localNewsCouldNotBeLoaded : 'Local news could not be loaded',
    pleaseWait : 'Please wait...',
    retry : 'Retry',
    search : 'Search',
    sendAnotherComment : 'Send another comment',
    showMore : 'Show More',
    showLess : 'Show Less',
    locationSettingNotAvailable : 'Sorry, location setting is not available for your location',
    useMyLocationNotAvailable : 'Sorry the "use my location" feature is not currently available',
    anErrorHasOccured : 'Sorry an error has occured, please try again',
    locationSettingIsNotCurrentlyAvailable : 'Sorry location setting is not currently available',
    locationYourLocationIs: "Your location is set to @",
    locationSettings: "Location Settings",
    errorTryingToDetectLocation : 'Sorry an error occured trying to detect your location. Please try again',
    searchResults : 'Search results:',
    searchTerm : 'Search Term',
    section : 'Sections',
    noResults : 'There were no results for',
    thereWasAProblem : 'There was a problem, please try again.',
    unableToDetectLocation : 'Unable to detect your location',
    useMyLocation : 'Use my location',
    locationBetweenCountries : 'Your chosen location falls between two counties. To set your location please select your nearest county to continue.',
    moreInfo : 'More information',
    lessInfo : 'Less information',
    errorAudio : 'Audio playback is unsupported on your device',
    errorLive : 'Live streaming is unsupported on your device',
    errorContent : 'This content is unavailable',
    errorDefault : 'Media playback is unsupported on your device',
    downloadMessageVideo : 'Choose from download options', //needs updating
    downloadMessageAudio : 'Download audio asset below', //placeholder in case it's used somewhere
    play : 'Play',
    nowPlaying : 'NOW PLAYING',
    mediaUnavailable : 'Media unavailable',
    latestSportStories: 'latest sport stories',
    moreStories: 'More stories',
    navMoreButton: 'More',
    navMoreLabel: ' sections',
    navFooterSectionsButton: 'Sections',
    streamRefreshError: "Sorry, we can't refresh the page.\nPlease try again later.",
    streamRefreshButton: 'Refresh updates',
    streamShowMoreButton: 'Show more updates',
    streamShowMoreError: "Sorry, we can't show more updates.\nPlease try again later.",
    offScreenMediaCaption: 'Media caption',
    live: "Live:",
    watch: "Watch:",
    constituencyMore: "Show More...",
    constituencySearchNoResults: "Sorry, no results found for '{postcode}'. Please enter a full UK postcode or use the <a href=\"/news/politics/constituencies\">Constituencies A-Z</a>",
    constituencySearchInternalError: "Sorry, we are currently unable to provide results for '{postcode}'. Please use the <a href=\"/news/politics/constituencies\">Constituencies A-Z</a>",
    constituencySearchConstituencyPath: "/news/politics/constituencies/"
});
